[package]
name = "ocr"
version.workspace = true
edition.workspace = true
publish = false
default-run = "ocr-train"

[dependencies]
oxide-forge = { path = "../../oxide-forge" }
image.workspace = true
serde.workspace = true
toml.workspace = true

[[bin]]
name = "ocr-train"
path = "src/bin/train.rs"

[[bin]]
name = "ocr-inference"
path = "src/bin/inference.rs"
